# https://github.com/LibraryOfCongress/bagit-python/issues/70
{% set name = "bagit" %}
{% set version = "1.6.0b6" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

# Needs to be built from a git checkout since it uses setuptools_scm
source:
  git_url: https://github.com/LibraryOfCongress/bagit-python.git
  git_rev: v{{ version }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - gettext
    - python
    - setuptools
    - setuptools_scm
  run:
    - gettext
    - python
    - setuptools

test:
  imports:
    - bagit
  commands:
    - bagit.py --version

about:
  home: https://libraryofcongress.github.io/bagit-python/
  summary: 'A Python library and command line utility for working with BagIt style packages.'
  license: Public-Domain
  dev_url: https://github.com/LibraryOfCongress/bagit-python
  doc_url: https://libraryofcongress.github.io/bagit-python/

extra:
  recipe-maintainers:
    - kwilcox
