{% set name = "bagit" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bagit-{{ version }}.tar.gz
  sha256: 9455006c2d1df88be95ec1fccabc5ea623389589ea4c85b3d85bd256f29d7656

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - bagit
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - bagit.py --version

about:
  home: https://libraryofcongress.github.io/bagit-python/
  license: LicenseRef-Public-Domain
  summary: Work with BagIt packages from Python
  dev_url: https://github.com/LibraryOfCongress/bagit-python
  doc_url: https://libraryofcongress.github.io/bagit-python/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
