# https://github.com/LibraryOfCongress/bagit-python/issues/70
{% set name = "bagit" %}
{% set version = "1.5.5" %}
{% set commit = "c0ba65714823c054b3a8b610e8967e70478204f3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/LibraryOfCongress/bagit-python.git
  git_rev: 613a82849d0dd43761e005606cd4c7ba3cd44188

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools

test:
  imports:
    - bagit
  commands:
    - bagit.py --version

about:
  home: https://libraryofcongress.github.io/bagit-python/
  summary: 'A Python library and command line utility for working with BagIt style packages.'
  license: Public-Domain
  dev_url: https://github.com/LibraryOfCongress/bagit-python
  doc_url: https://libraryofcongress.github.io/bagit-python/

extra:
  recipe-maintainers:
    - kwilcox
