{% set name = "bagit" %}
{% set version = "1.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bagit-{{ version }}.tar.gz
  sha256: 37df1330d2e8640c8dee8ab6d0073ac701f0614d25f5252f9e05263409cee60c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
  run:
    - python >=3

test:
  imports:
    - bagit
  requires:
    - pip
  commands:
    - pip check
    - bagit.py --version

about:
  home: https://libraryofcongress.github.io/bagit-python/
  license: LicenseRef-Public-Domain
  summary: Work with BagIt packages from Python
  dev_url: https://github.com/LibraryOfCongress/bagit-python
  doc_url: https://libraryofcongress.github.io/bagit-python/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
