travis:
  secure:
    BINSTAR_TOKEN: OmdnfWPHsWgRA/ZGB593RxGVRL0VYYTibK9OGgicbhlpbDAYIVFnbhh8c2AgCxDub54QfDguwmdnSBUx5DADQA+NErINnB7mHBTfUfYAw70uGReD5pFFfWdklE3msKiJ6U3jSL8Vn3kPWs7xTJtOqAbSHTZc9bOD+qvlEf62gF/fM5GX6OsaSfjTBLk4UBB/+nSM8LJYaiftY2jMkhDwSExF6F4+bZ3ZCBuJj3HvPIOW6dEzQjVRIa5TyBqicZjZPcPDHtEJ18UBUSIauRK0IwvGoU7n+XOra/gCIxZByBs8bMbs+YeitKp2Bja2ugKuGzcTnN1S1n+GRWXWUVxhxY5hD9cT6AENivSeLVhTENVnrkZcbNhUnptb9k4gGrlnmrKj1fiP9jLVIeNYCpBPPltoHyVQQxx61lEnubSOcKDTvbQHUZQAP2irbyMoRY/CbQawzqnqfzbyIi0r3tmJPsgxSLRqFV7/Na3VhB0ApMBFWoyvT++boozhPVk/Zvx02SvbjuRME6+UGVXTJ9g6PzpYhakoYzQ4/jHfv9axgsfasriu34KC0wn84kJ6vCxzxLl6iYAcwohXh0B0edHRUhWytK/BTGJPeTdET0TwcXedVKidj+KWNmBueU/FNvVYYqz8UOh7KigSLECHwOjBTb+sDstLeKO5FnEUxXxf+WU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
