travis:
  secure:
    BINSTAR_TOKEN: cZkYuwhVl+jHyziDLJCaihwBLSSpXlWMnnjWpr4tPa/KUr9YTo5c/tf7sHDVKmDhFJaO+QHkhuioeEfPNOL6X2VgQgbdjvhdS7mbEJK/hRPR/p9okSl6hKN3lualekldu9DdQDvitSF8HrnBNYawbWPSaSiV/M9zflJkz/IgmOa9zv6eaNOkV49R11cNWlbhCHbSVvK3zbNL5P3GZ3+X83TaZxDW5XkygGtfDi2IVje2M69avPj9ZiuwjkfFB6hyJUfG94Xh3mPR8sDZ4PUYQaSHwHrSEEZXsXyaW5wjMc/tb2wuexx/M4j2hY5nsKL8VJzqn4OyyErzTCyVOwaklge4quM5jnu8fCEIGH0A+eB1HKwK3UMVRyl0zIUpttMWLRZZFyGZ2fcYyuFZmm+5mJJECEVICZ0+qxnWPZ3zAdQlbeGMTLZo8aA296rvZGGooydzVAo0J6joEwHjTpzPefHe4/UBtA1HHYnLMl1SeLgF366C3fO7oZZ9XpVEiG6gxghY7DlUa6iHAN/99YIc4V0p28jy0nLBskk1xVpWsNUcs21orOVLfsJHS+t7uzzTRZt6MzX0Jyhctsbp7hdEE3g7XgJ0XMZ3IEMmN9TEhSnrWJlJDZFZay1g67OKvAXF1ow0XQboOboMg0W991Eqmp0rTBfdkv9PIShRfy9oy1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
